name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean buildozer cache
        run: |
          rm -rf .buildozer || true
          rm -rf bin || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            git zip unzip curl \
            build-essential autoconf automake libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            libffi-dev libssl-dev libsqlite3-dev \
            libjpeg-dev libpng-dev libfreetype6-dev \
            cmake ccache \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - name: Install Android cmdline-tools (sdkmanager)
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -L -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdline-tools.zip
          mv cmdline-tools latest
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

      - name: Install Android SDK packages + accept licenses
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2"

      - name: Install buildozer + cython
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install "Cython<3" "buildozer==1.5.0"

      - name: Build APK (debug)
        run: |
          buildozer -v android debug 2>&1 | tee build.log

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: PLU_APP-debug-apk
          path: bin/*.apk
          if-no-files-found: error

      - name: Upload build log (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log
