name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential git zip unzip openjdk-17-jdk \
            python3-dev python3-pip \
            autoconf automake libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            libffi-dev libssl-dev libsqlite3-dev \
            libjpeg-dev libpng-dev \
            cmake ccache

      - name: Install buildozer + cython
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install "cython<3" buildozer

      - name: Ensure/patch buildozer.spec (accept licenses)
        run: |
          python - <<'PY'
          from pathlib import Path
          import re, textwrap

          p = Path("buildozer.spec")
          if not p.exists():
              content = textwrap.dedent("""\
              [app]
              title = PLU App
              package.name = pluapp
              package.domain = org.tuniche
              version = 0.1

              source.dir = .
              source.include_exts = py,kv,png,jpg,jpeg,csv

              requirements = python3,kivy,pillow,openpyxl

              android.api = 33
              android.minapi = 24
              android.archs = arm64-v8a
              orientation = portrait
              """)
              p.write_text(content, encoding="utf-8")

          txt = p.read_text(encoding="utf-8")

          # Si no existe la línea, la agrega. Si existe, la fuerza a True.
          if re.search(r'^\s*android\.accept_sdk_license\s*=', txt, flags=re.M):
              txt = re.sub(r'^\s*android\.accept_sdk_license\s*=.*$',
                           'android.accept_sdk_license = True',
                           txt, flags=re.M)
          else:
              # la agrega al final
              txt = txt.rstrip() + "\n\nandroid.accept_sdk_license = True\n"

          p.write_text(txt, encoding="utf-8")
          print("buildozer.spec patched: android.accept_sdk_license = True")
          PY

      - name: Build APK (debug) - auto accept prompts
        run: |
          yes | buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: PLU_APP-APK
          path: bin/*.apk
