name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            git zip unzip curl \
            build-essential pkg-config \
            libssl-dev libffi-dev \
            zlib1g-dev libbz2-dev liblzma-dev \
            libjpeg-dev libpng-dev \
            libsqlite3-dev \
            libncurses5-dev libncursesw5-dev \
            libreadline-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Android SDK cmdline-tools + set env
        run: |
          export ANDROID_SDK_ROOT="$HOME/android-sdk"
          export ANDROID_HOME="$ANDROID_SDK_ROOT"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"

          cd "$RUNNER_TEMP"
          curl -L -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdline-tools.zip
          mv cmdline-tools "$ANDROID_SDK_ROOT/cmdline-tools/latest"

          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Install Android packages + accept licenses
        run: |
          yes | sdkmanager --licenses
          sdkmanager \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2"

      - name: Install buildozer + cython + pinned python-for-android
        run: |
          python -m pip install "cython<3" "buildozer==1.5.0" "python-for-android==2024.1.21"

      - name: Build APK (debug) and save logs
        run: |
          set -o pipefail
          buildozer -v android debug 2>&1 | tee build.log

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk

